#==============主服务配置==============#
[app]
# 项目名称
AppName             = "App"
# 启动模式：release、test、debug
SetMode             = "debug"
# 启动端口
HttpPort            = "8080"
# 配置文件是否热加载，这里不建议开启。1开启、0关闭
IsOnConfigChange    = 0
# 慢请求阈值（单位秒）
SlowReqThreshold    = 3

## 限流器，保护服务器过载出现不可预期的错误
# 请求最大令牌数(每秒会产生100个令牌)
ReqBurst            = 1000


## https验证
# cert证书路径（绝对路径）
CertFile    = ""
# #key证书路径（绝对路径）（当certFile，keyFile都存在时将使用HTTPS协议
KeyFile     = ""

## 日志记录目录
# 日志跟目录，绝对路径
DLogRootPath            = "E:/logs/"
# 日志级别 fatal、panic、error、warn、info、debug
DLogSetLevel            = "info"
# 日志文件最大大小，单位兆，0不限制大小
DLogMaxSize             = 0
# 日志文件最大保存天数，如果设置，不建议设置太多，避免一次性处理的文件太多造成卡顿
DLogMaxAge              = 0
# 每日N点开始执行陈旧文件处理，陈旧文件含义建立在DLogMaxAge参数之上，当DLogMaxAge为0时不会触发
DLogMillEveryDayHour    = 0
# 是否同时输出到控制台。1是、0否。当SetMode为“debug”模式时同样会输出到控制台
DLogIsInStdout          = 1