#==============正式环境==============#
[release]
[release.signAccountSecret]   # 签名秘钥
app     = "aaaaaaaa"

[release.aesAccountSecret]  # 如意购默认aes密钥
default = "bbbbbbbb"

#==============测试环境==============#
[test]
[test.signAccountSecret]   # 签名秘钥
app     = "aaaaaaaa"

[test.aesAccountSecret]  # 如意购默认aes密钥
default = "bbbbbbbb"


#==============调试环境==============#
[debug]
[debug.signAccountSecret]   # 签名秘钥
app     = "aaaaaaaa"

[debug.aesAccountSecret]  # 如意购默认aes密钥
default = "bbbbbbbb"