#==============正式环境==============#
[release]
[release.callHost]   # 调用地址
shop = 'http://127.0.0.1'

#==============测试环境==============#
[test]
[test.callHost]   # 调用地址
shop = 'http://127.0.0.1'


#==============调试环境==============#
[debug]
[debug.callHost]   # 调用地址
shop = 'http://127.0.0.1'
