#==============正式环境==============#
[release]
[release.mysql.default]
Host            = "127.0.0.1"       # 主机
Port            = "3306"            # 端口
Username        = "root"            # 用户名
Password        = "root"            # 密码
Database        = "dlog"            # 数据库名称
Prefix          = "dlog_"           # 数据库表前缀
Charset         = "utf8"            # 数据库编码
MaxIdleConns    = 50                # 最大空闲连接数
MaxOpenConns    = 40000             # 最大打开的连接数



#==============测试环境==============#
[test]
[test.mysql.default]
Host            = "127.0.0.1"       # 主机，为空时不进行初始化
Port            = "3306"            # 端口
Username        = "root"            # 用户名
Password        = "root"            # 密码
Database        = "dlog"            # 数据库名称
Prefix          = "dlog_"           # 数据库表前缀
Charset         = "utf8"            # 数据库编码
MaxIdleConns    = 50                # 最大空闲连接数
MaxOpenConns    = 40000             # 最大打开的连接数

[test.redis.default]
Host            = "127.0.0.1"     # 主机，为空时不进行初始化
Port            = "12345"         # 端口
Password        = ""              # 密码
DB              = 0               # 数据库
MinIdleConns    = 10              # 最小空闲连接数，在启动阶段创建指定数量的Idle连接
MaxIdleConns    = 50              # 最大空闲链接数



#==============调试环境==============#
[debug]
[debug.mysql.default]
Host            = "127.0.0.1"       # 主机，为空时不进行初始化
Port            = "3306"            # 端口
Username        = "root"            # 用户名
Password        = "root"            # 密码
Database        = "dlog"            # 数据库名称
Prefix          = "dlog_"           # 数据库表前缀
Charset         = "utf8"            # 数据库编码
MaxIdleConns    = 50                # 最大空闲连接数
MaxOpenConns    = 40000             # 最大打开的连接数

[debug.redis.default]
Host            = "127.0.0.1"     # 主机，为空时不进行初始化
Port            = "12345"         # 端口
Password        = ""              # 密码
DB              = 0               # 数据库
MinIdleConns    = 10              # 最小空闲连接数，在启动阶段创建指定数量的Idle连接
MaxIdleConns    = 50              # 最大空闲链接数